### ISSUE TITLE
Refactor the tests to make sure all tests work

### ISSUE THREAD

**Issue by yanhao-li** [4115-viz/viz#11]
priority: low

**Comment by yanhao-li** [comment]
We should decouple the format functions from testing. i.e. An update(eg. add/remove spaces) on formatter should not fail the tests. The tests should be fully based on the underhood data structure.

**Comment by Matt20D** [comment]
I dont know what this means? 

First of all it absolutely should fail, because it is a hint as to there is something we need to look into. Second, I have not looked at scanner, parser, or semantic flag tests. Those still fail, and will likely fail until the due deadline when they reflect our final format for everything. 

There is no easy way to look at the "underhood data structure". So the easiest way to test behavior is to compare .ref and .out files. This is how nearly all projects do things. Further, its too late in the game to try and change things now.

The program tests that are failing, is because something was changed causing .out and .ref files for programs to differ. This is desired behavior. When a new feature is added, then all program tests need to be updated to reflect it, especially if it alters previous behavior.

I haven't looked at the format functions in 3 weeks, so I don't know what you mean. 

The only tests that anyone should be looking at are the programs directory. However for debugging I personally use the -ts -a and -s flags to see how things are mapping.

Sorry for the long winded answer, but I don't know what you are referring to. I feel like its not a good use of our time to be overhauling testing infrastructure.
